const {Schema, model} = require('mongoose');

const Devices = new Schema({
    Status : {type:Number, default: 0},
    Name : { type:String},
    User : { type:String},
    IP : { type:String},
    System : { type:String},
    Serial_Number : { type:String},
    Manufacturer : { type:String},
    Model : { type:String},
    Location : { type:String},
    Uptime : { type:String},
    date: { type: Date },
    numFiles : { type:Number},
    Administrators:{ type:String},
    DbHome:{ type:String},
    Listener:{ type:String},
    TnsNames:{ type:String},
    PdfTask:{ type:String},
    RebootTask:{ type:String},
    CountryId:{ type:String},
    CurrencyId:{ type:String},
    RegionId:{ type:String},
    StoreNumber:{ type:String},
    StoreName:{ type:String},
    InstallEnv:{ type:String},
    TerminalId:{ type:String},
    IsPosLead:{ type:String},
    IsXServices:{ type:String},
    EnvDbUrl:{ type:String},
    EnvDbHost:{ type:String},
    XstoreConnectionUrl:{ type:String},
    XstoreConnectionHost:{ type:String},
    IsMonitored:{ type:String},
    IsSccmClient:{ type:String},
    Uptime:{ type:String},
    ChassisType:{ type:String},
    ExpirationDays:{ type:String},
    XStoreVersion:{ type:String},
    XEnvVersion:{ type:String},
    InstallxRegistryEnv:{ type:String},
    PosPollDisabled:{ type:String}

});

module.exports= model('devices',Devices,'devices');